// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oeeggwjdnwxtcduardit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lZWdnd2pkbnd4dGNkdWFyZGl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDY5NDIsImV4cCI6MjA2NDAyMjk0Mn0.xjwiLzCXGgddZgwuxk5WBqcdnh1hk36bBYXJMgYefhI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);